spring:
  datasource:
    url: jdbc:mysql://${PROD_DB_HOST}:${PROD_DB_PORT}/${PROD_DB_NAME}
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
    name: spring-blog
    driver-class-name: com.mysql.cj.jdbc.Driver

springdoc:
  swagger-ui:
    tags-sorter: alpha
    operations-sorter: alpha
    path: /swagger-ui-custom.html


