server:
  port: 5000
  servlet:
    session:
      timeout: 3600

spring:
  datasource:
    url: jdbc:mysql://localhost:3308/bg
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
#  security:
#    oauth2:
#      resource-server:
#        jwt:
#          jwk-set-uri: https://www.googleapis.com/service_accounts/v1/jwk/securetoken@system.gserviceaccount.com
#          issuer-uri: https://securetoken.google.com/${bikego-8f323}
#      user:
#        name: admin
#        password: 123

  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        enable_lazy_load_no_trans=true:

  #Swagger
#localhost:8090/bikego/swagger-ui.html
springdoc:
  swagger-ui:
    tags-sorter: alpha
    operations-sorter: alpha
    path: /swagger-ui-custom.html




